(function(){
const D=window.NMT_DATA,R=window.NMT_REASONING;
const STORAGE='nmt-clinical-reasoning-v0.1';
const defaultState={route:'reasoning',draftComplaint:'',active:null,history:[],detail:null};
let state=load();
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function uid(){return 's_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function current(){return state.active}
function setRoute(route,detail=null){state.route=route;state.detail=detail;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function newSession(complaint,pathwayId){state.active={id:uid(),createdAt:new Date().toISOString(),complaint,pathwayId,answers:{},reassessment:{},status:'active'};save();render()}
function archiveActive(){if(!state.active)return;state.active.status='saved';state.active.updatedAt=new Date().toISOString();state.history=[state.active,...state.history.filter(x=>x.id!==state.active.id)];state.active=null;save();render()}
function answer(id,value){state.active.answers[id]=value;state.active.updatedAt=new Date().toISOString();save();render()}
function resetAnswer(id){delete state.active.answers[id];save();render()}

function render(){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));const app=document.getElementById('app');if(state.route==='reasoning')app.innerHTML=reasoningView();if(state.route==='anatomy')app.innerHTML=anatomyView();if(state.route==='movement')app.innerHTML=movementView();if(state.route==='observation')app.innerHTML=observationView();if(state.route==='sessions')app.innerHTML=sessionsView();bindDynamic()}

function reasoningView(){
  if(state.detail?.type==='muscle')return muscleDetail(state.detail.id,'reasoning');
  if(state.detail?.type==='movement')return movementDetail(state.detail.id,'reasoning');
  if(!current())return startView();
  const s=current(), path=D.PATHWAYS[s.pathwayId], summary=R.buildSummary(s.pathwayId,s.answers,D,s.reassessment||{});
  if(summary.safety.escalate)return `<section class="hero"><p class="eyebrow">safety boundary</p><h2>Leave the muscle-speculation pathway here.</h2></section><section class="red-flag"><h2>Professional medical evaluation is appropriate.</h2><p>${esc(summary.safety.message)}</p><p class="small">The app detected a response that can overlap with neurological, traumatic, systemic, abdominal, or urinary problems. It will not keep narrowing this into a muscle hypothesis.</p><div class="button-row"><button class="secondary-btn" data-action="review-answers">Review answers</button><button class="primary-btn" data-action="save-session">Save session</button></div></section>${answerReview(s)}`;
  const next=summary.nextQuestion;
  return `<section class="hero"><p class="eyebrow">active reasoning map</p><h2>${esc(s.complaint)}</h2><p>${esc(path.name)} · hypotheses update as answers change.</p></section>
  ${next?questionCard(next,s.answers[next]):`<section class="notice"><strong>Question set complete.</strong> Review the current reasoning, try only tolerable observations, then record reassessment.</section>`}
  ${hypothesesSection(summary.hypotheses)}
  ${next?'':reassessmentSection(s)}
  <div class="section-title"><h3>Inspect the reasoning</h3><p>Nothing is locked.</p></div>${answerReview(s)}
  <div class="button-row" style="margin-top:16px"><button class="secondary-btn" data-action="save-session">Save session</button><button class="ghost-btn" data-action="start-over">Start a different complaint</button></div>`;
}
function startView(){return `<section class="hero"><p class="eyebrow">observe → ask → reason → compare</p><h2>Start with ordinary language.</h2><p>Describe the complaint or movement problem. V0.1 currently knows two deliberately small reasoning neighborhoods: neck/scapula/serratus/pull-up and low-back/hip-extension.</p></section><section class="card stack"><label><span class="field-label">What are you noticing?</span><textarea id="complaintInput" placeholder="Examples: My lower back hurts and it is hard to straighten up after sitting. / My side under the shoulder blade hurts during pull-ups and my neck is tight.">${esc(state.draftComplaint)}</textarea></label><div class="button-row"><button class="primary-btn" data-action="analyze-complaint">Build reasoning map</button><button class="secondary-btn" data-pathway-start="upper">Use upper-quarter prototype</button><button class="secondary-btn" data-pathway-start="lower">Use low-back prototype</button></div><p class="small muted">Educational tool only. It does not diagnose conditions or assign fake certainty percentages.</p></section>`}
function questionCard(q,selected){return `<section class="question-card"><span class="pill">next discriminator</span><h3>${esc(q.text)}</h3><div class="choice-row">${q.options.map(o=>`<button type="button" class="choice ${selected===o?'selected':''}" data-answer-id="${q.id}" data-answer-value="${esc(o)}">${esc(o)}</button>`).join('')}</div><details class="why-box"><summary>Why are you asking?</summary><p>${esc(q.why)}</p></details></section>`}
function hypothesesSection(items){if(!items.length)return '';return `<div class="section-title"><h2>Worth examining now</h2><p>Ranked by rule support, not diagnostic probability.</p></div><div class="grid two">${items.slice(0,6).map((h,i)=>`<article class="hypothesis-card"><header><div><span class="pill ${i===0?'good':''}">${i===0?'more consistent now':'also worth considering'}</span><h3>${esc(h.name)}</h3></div></header><div><strong>Why it is being considered</strong><ul class="clean">${h.support.slice(0,3).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${h.weaken.length?`<div><strong>What weakens it</strong><ul class="clean">${h.weaken.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<div><strong>Look next</strong><p class="small muted">${esc(nextLook(h.id))}</p></div><div class="button-row"><button class="small-btn" data-open-muscle="${h.id}">Related anatomy</button>${h.muscle?.movements?.[0]?`<button class="small-btn" data-open-movement="${h.muscle.movements[0]}">Related movement</button>`:''}</div></article>`).join('')}</div>`}
function nextLook(id){const map={
 'serratus-anterior':'Compare winging/shrugging during a wall slide or wall push, then compare with an assisted hang.',
 'lower-trapezius':'Observe whether upward rotation improves when shrugging is reduced and the arm moves slowly.',
 'levator-scapulae':'Compare cervical rotation/side-bending and shoulder elevation side to side.',
 'upper-trapezius':'Compare early shrug behavior rather than treating perceived tightness as proof of shortening.',
 'latissimus-dorsi':'Compare supported overhead range with and without lumbar extension compensation.',
 'rotator-cuff':'Compare pain-free shoulder rotation/control with scapula supported.',
 'iliopsoas':'Compare hip extension with lumbar extension; note whether hip position changes the back complaint.',
 'lumbar-erectors':'Keep the hip neutral and compare small lumbar extension, flexion, and return to upright.',
 'multifidus':'Look for segmental/asymmetric control rather than trying to palpate a diagnosis.',
 'quadratus-lumborum':'Compare side-bending and rib-to-pelvis loading on each side.'}; return map[id]||'Compare the relevant action with a neighboring-joint position change.'}
function answerReview(s){const ids=D.PATHWAYS[s.pathwayId].questions.filter(id=>s.answers[id]!=null);if(!ids.length)return '';return `<section class="card" id="answerReview"><h3>Answered so far</h3>${ids.map(id=>{const q=D.QUESTIONS[id];return `<div class="list-row"><div><strong>${esc(q.text)}</strong><span class="small muted">${esc(s.answers[id])}</span></div><button class="small-btn" data-reset-answer="${id}">change</button></div>`}).join('')}</section>`}
function reassessmentSection(s){const r=s.reassessment||{}, candidates=R.scoreHypotheses(s.pathwayId,s.answers,D,{});return `<div class="section-title"><h2>Reassess</h2><p>The hypothesis can change.</p></div><section class="card reassessment-grid"><label><span class="field-label">What structure or movement relationship did you aim to test?</span><select id="reassessTarget" class="input"><option value="">Choose…</option>${candidates.map(h=>`<option value="${h.id}" ${r.target===h.id?'selected':''}>${esc(h.name)}</option>`).join('')}</select></label><label><span class="field-label">After that conservative change, what happened?</span><select id="reassessChange" class="input"><option value="">Choose…</option>${['improved','unchanged','worse','different location'].map(v=>`<option ${r.change===v?'selected':''}>${v}</option>`).join('')}</select></label><label><span class="field-label">Range / movement quality</span><select id="reassessRange" class="input"><option value="">Choose…</option>${['smoother / more range','same','less range / more guarded'].map(v=>`<option ${r.range===v?'selected':''}>${v}</option>`).join('')}</select></label><label><span class="field-label">Notes</span><textarea id="reassessNotes" placeholder="What did you try, and what changed?">${esc(r.notes||'')}</textarea></label><button class="primary-btn" data-action="save-reassessment">Update reassessment</button></section>`}

function anatomyView(){if(state.detail?.type==='muscle')return muscleDetail(state.detail.id,'anatomy');return `<section class="hero"><p class="eyebrow">cross-linked anatomy</p><h2>Functional anatomy, not flash cards.</h2><p>Each record connects actions, relationships, observations, movements, intervention categories, and source provenance.</p></section><section class="card"><input id="anatomySearch" class="input" placeholder="Search muscles or region…"></section><div class="grid three" style="margin-top:14px" id="anatomyGrid">${D.MUSCLES.map(m=>muscleCard(m)).join('')}</div>`}
function muscleCard(m){return `<article class="record-card" data-search-text="${esc((m.name+' '+m.region+' '+m.group).toLowerCase())}"><span class="pill">${esc(m.region)}</span><h3>${esc(m.name)}</h3><p class="small muted">${esc(m.action.slice(0,2).join(' · '))}</p><button class="link-btn" data-open-muscle="${m.id}">Open functional record →</button></article>`}
function muscleDetail(id,returnRoute){const m=D.MUSCLES.find(x=>x.id===id);if(!m)return '<div class="empty">Record not found.</div>';const sources=(m.sourceIds||[]).map(id=>D.SOURCES[id]).filter(Boolean);return `<button class="ghost-btn" data-back-detail="${returnRoute}">← Back</button><section class="record-card" style="margin-top:12px"><p class="eyebrow">${esc(m.region)} · ${esc(m.group)}</p><h2>${esc(m.name)}</h2><div class="facts"><div class="fact"><strong>Origin</strong>${esc(m.origin)}</div><div class="fact"><strong>Insertion</strong>${esc(m.insertion)}</div><div class="fact"><strong>Action / function</strong><ul class="clean">${m.action.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="fact"><strong>Innervation</strong>${esc(m.innervation)}</div><div class="fact"><strong>Functional roles</strong><ul class="clean">${(m.roles||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="fact"><strong>Related structures</strong><div class="relation-list">${[...(m.synergists||[]),...(m.compensators||[])].filter((x,i,a)=>a.indexOf(x)===i).map(r=>muscleRelation(r)).join('')||'<span class="muted small">Starter record</span>'}</div></div><div class="fact"><strong>Related movements</strong><div class="relation-list">${(m.movements||[]).map(r=>`<button class="relation-chip" data-open-movement="${r}">${esc(nameForMovement(r))}</button>`).join('')}</div></div><div class="fact"><strong>Conservative categories</strong><ul class="clean">${(m.interventions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${sources.length?`<div class="fact"><strong>Sources</strong>${sources.map(s=>`<p class="source">${esc(s.publisher)} — ${esc(s.title)}<br>${esc(s.url)}</p>`).join('')}</div>`:''}</div></section>`}

function movementView(){if(state.detail?.type==='movement')return movementDetail(state.detail.id,'movement');return `<section class="hero"><p class="eyebrow">movement library</p><h2>Movement → muscles → observations.</h2><p>The starter set proves two-way navigation and multiplanar functional reasoning without becoming an exercise catalog.</p></section><div class="grid three">${D.MOVEMENTS.map(m=>`<article class="record-card"><span class="pill">${esc(m.planes.join(' · '))}</span><h3>${esc(m.name)}</h3><p class="small muted">${esc(m.demands.slice(0,2).join(' · '))}</p><button class="link-btn" data-open-movement="${m.id}">Open movement analysis →</button></article>`).join('')}</div>`}
function movementDetail(id,returnRoute){const m=D.MOVEMENTS.find(x=>x.id===id);if(!m)return '<div class="empty">Movement not found.</div>';return `<button class="ghost-btn" data-back-detail="${returnRoute}">← Back</button><section class="record-card" style="margin-top:12px"><p class="eyebrow">movement analysis</p><h2>${esc(m.name)}</h2><div class="facts"><div class="fact"><strong>Planes</strong>${esc(m.planes.join(', '))}</div><div class="fact"><strong>Primary joints / regions</strong>${esc(m.joints.join(', '))}</div><div class="fact"><strong>Primary muscular demands</strong><div class="relation-list">${m.muscles.map(id=>muscleRelation(id)).join('')}</div></div><div class="fact"><strong>Stabilizers</strong>${esc(m.stabilizers.join(', '))}</div><div class="fact"><strong>Neuromuscular / mobility demands</strong><ul class="clean">${m.demands.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="fact"><strong>Common compensations</strong><ul class="clean">${m.compensations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="fact"><strong>Regression</strong>${esc(m.regression)}</div><div class="fact"><strong>Progression</strong>${esc(m.progression)}</div></div></section>`}

function muscleRelation(id){const found=D.MUSCLES.find(x=>x.id===id);return found?`<button class="relation-chip" data-open-muscle="${id}">${esc(found.name)}</button>`:`<span class="relation-chip relation-static">${esc(nameForMuscle(id))} <small>record later</small></span>`}
function observationView(){return `<section class="hero"><p class="eyebrow">observation ≠ diagnosis</p><h2>Notice the pattern first. Interpret it second.</h2><p>These starter observations show what may be worth comparing next without converting a visible pattern directly into a single muscle explanation.</p></section><div class="grid two">${D.OBSERVATIONS.map(o=>`<article class="record-card"><span class="pill">observation</span><h3>${esc(o.name)}</h3><div class="fact"><strong>Possible contributors</strong><ul class="clean">${o.possible.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="fact"><strong>Look next</strong><ul class="clean">${o.lookNext.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></article>`).join('')}</div>`}
function sessionsView(){return `<section class="hero"><p class="eyebrow">local-first records</p><h2>Sessions, reassessment, backup.</h2><p>Reasoning sessions stay on this device unless you export them.</p></section><section class="card"><div class="button-row"><button class="primary-btn" data-action="export-json">Export JSON</button><label class="secondary-btn" style="cursor:pointer">Import JSON<input id="importJson" type="file" accept="application/json" hidden></label></div></section><div class="section-title"><h2>Saved sessions</h2><p>${state.history.length} saved</p></div>${state.history.length?`<div class="stack">${state.history.map(s=>`<article class="session-card"><span class="pill">${esc(D.PATHWAYS[s.pathwayId]?.name||s.pathwayId)}</span><h3>${esc(s.complaint)}</h3><p class="small muted">${new Date(s.createdAt).toLocaleString()}</p><div class="button-row"><button class="small-btn" data-load-session="${s.id}">Open</button><button class="small-btn danger-btn" data-delete-session="${s.id}">Delete</button></div></article>`).join('')}</div>`:'<div class="empty">No saved sessions yet.</div>'}`}
function nameForMuscle(id){return D.MUSCLES.find(x=>x.id===id)?.name||id.replaceAll('-',' ')}function nameForMovement(id){return D.MOVEMENTS.find(x=>x.id===id)?.name||id.replaceAll('-',' ')}
function bindDynamic(){
  document.querySelectorAll('[data-answer-id]').forEach(b=>b.onclick=()=>answer(b.dataset.answerId,b.dataset.answerValue));
  document.querySelectorAll('[data-reset-answer]').forEach(b=>b.onclick=()=>resetAnswer(b.dataset.resetAnswer));
  document.querySelectorAll('[data-open-muscle]').forEach(b=>b.onclick=()=>{state.detail={type:'muscle',id:b.dataset.openMuscle};save();render()});
  document.querySelectorAll('[data-open-movement]').forEach(b=>b.onclick=()=>{state.detail={type:'movement',id:b.dataset.openMovement};save();render()});
  document.querySelectorAll('[data-back-detail]').forEach(b=>b.onclick=()=>{state.detail=null;state.route=b.dataset.backDetail;save();render()});
  document.querySelectorAll('[data-pathway-start]').forEach(b=>b.onclick=()=>{const p=b.dataset.pathwayStart;newSession(p==='upper'?'My side/serratus area hurts with pull-ups and my neck feels tight.':'My lower back hurts and it is hard to straighten up after sitting.',p)});
  const a=document.querySelector('[data-action="analyze-complaint"]');if(a)a.onclick=()=>{const input=document.getElementById('complaintInput');const complaint=input.value.trim();state.draftComplaint=complaint;const path=R.detectPathway(complaint,D);if(!complaint){input.focus();return}if(path)newSession(complaint,path.id);else{input.insertAdjacentHTML('afterend','<p class="notice small">V0.1 does not yet have a validated reasoning neighborhood for that description. Choose one of the two prototype pathways rather than forcing a bad match.</p>')}};
  const reviewBtn=document.querySelector('[data-action="review-answers"]');if(reviewBtn)reviewBtn.onclick=()=>document.getElementById('answerReview')?.scrollIntoView({behavior:'smooth',block:'start'});
  const saveBtn=document.querySelector('[data-action="save-session"]');if(saveBtn)saveBtn.onclick=archiveActive;
  const startOver=document.querySelector('[data-action="start-over"]');if(startOver)startOver.onclick=()=>{if(confirm('Start a different complaint? The active session will be saved first.')){archiveActive();state.route='reasoning';render()}};
  const reassess=document.querySelector('[data-action="save-reassessment"]');if(reassess)reassess.onclick=()=>{state.active.reassessment={target:document.getElementById('reassessTarget').value,change:document.getElementById('reassessChange').value,range:document.getElementById('reassessRange').value,notes:document.getElementById('reassessNotes').value};save();render()};
  const search=document.getElementById('anatomySearch');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll('[data-search-text]').forEach(el=>el.style.display=el.dataset.searchText.includes(q)?'':'none')};
  document.querySelectorAll('[data-load-session]').forEach(b=>b.onclick=()=>{const found=state.history.find(x=>x.id===b.dataset.loadSession);if(found){state.active=JSON.parse(JSON.stringify(found));state.active.status='active';state.route='reasoning';state.detail=null;save();render()}});
  document.querySelectorAll('[data-delete-session]').forEach(b=>b.onclick=()=>{if(confirm('Delete this saved session?')){state.history=state.history.filter(x=>x.id!==b.dataset.deleteSession);save();render()}});
  const exp=document.querySelector('[data-action="export-json"]');if(exp)exp.onclick=()=>{const blob=new Blob([JSON.stringify({schema:'nmt-clinical-reasoning-v0.1',exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='clinical-reasoning-backup.json';a.click();URL.revokeObjectURL(a.href)};
  const imp=document.getElementById('importJson');if(imp)imp.onchange=async()=>{try{const parsed=JSON.parse(await imp.files[0].text());if(parsed.schema!=='nmt-clinical-reasoning-v0.1'||!parsed.state)throw new Error('Wrong schema');state={...defaultState,...parsed.state,route:'sessions',detail:null};save();render()}catch(e){alert('Import failed: '+e.message)}};
}

document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>setRoute(b.dataset.route));document.getElementById('helpBtn').onclick=()=>document.getElementById('helpDialog').showModal();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
render();
})();
